### ISSUE TITLE
Incoming calls not working Voice React Native SDK

### ISSUE THREAD

**Issue by spaculusaninja** [twilio/twilio-voice-react-native#432]
# Issue

## Pre-submission Checklist
- [ ] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
After following the setup steps for Android and ios in the Twilio Voice React Native SDK documentation (version 1.2.0), I was able to successfully register for incoming calls, as indicated by the Successfully registered for incoming calls message in the voice.on(Voice.Event.Registered) event. However, incoming calls do not seem to work as expected afterward. No incoming call notifications or callbacks are triggered.

## Reproduction Steps
1. Completed all steps as described in the Twilio Voice React Native SDK documentation.
2. Set up a Firebase project and linked it for FCM.
3. Followed instructions for Twilio Push for FCM HTTP v1 API as described[ here](https://help.twilio.com/articles/20768292997147-Updating-Twilio-Push-for-FCM-HTTP-v1-API).
4. Registered for incoming calls using the Twilio SDK with:
voice.on(Voice.Event.Registered, () => {
    console.log('Successfully registered for incoming calls');
});
5.No further events or notifications were triggered for incoming calls.

## Expected Behavior
Incoming calls should trigger an appropriate event or notification, and the voice.on(Voice.Event.CallInvite) event should be fired when a call is received.

## Actual Behavior
After the "Successfully registered for incoming calls" message, incoming calls are not detected by the app. No event is triggered, and the incoming call is not received.

## Reproduction Frequency
The issue occurs 100% of the time.

## Software and Device Information
Device: [e.g. Oppo F21 pro, iphone 14]
OS: [e.g. Android 14, ios 17]
React version: 18.2.0
React Native version: 0.74.3
Node version: 18.17.0
npm version: 9.6.7
Twilio Voice React Native SDK version: 1.2.0

**Comment by mhuynh5757** [comment]
Hello @spaculusaninja thanks for reaching out. Are you using `@react-native-firebase/messaging` in your application alongside our SDK? There are known issues with using both that our team is trying to resolve.

**Comment by mhuynh5757** [comment]
Hi @spaculusaninja we're close to merging a fix to `main`, please sit tight! After merging this week, we'll also cut a release this week. But in the meantime, if you're feeling adventurous and don't mind testing the branch before we merge, that's also an option for you. The branch is `task/disable-firebase-service`.

**Comment by spaculusaninja** [comment]
"Hi @mhuynh5757,

Thank you for your quick response and for working on the fix. I appreciate your efforts to merge the solution to the main branch and plan for a release this week.

Following your suggestion, I decided to test the 'task/disable-firebase-service' branch. I carefully followed the instructions provided in the documentation (https://github.com/twilio/twilio-voice-react-native/blob/main/docs/out-of-band-firebase-messaging-service.md). However, I'm still experiencing issues with push notifications and incoming calls in the Voice React Native SDK.

Could you please provide any additional troubleshooting steps or insights that might help resolve these persistent issues? Are there any known limitations or specific configurations that I should be aware of when testing this branch?
![Uploading Screenshot 2024-10-24 at 5.51.27 PM.png…]()

**Comment by spaculusaninja** [comment]
![Uploading Screenshot 2024-10-24 at 6.01.31 PM.png…]()

**Comment by spaculusaninja** [comment]
[Screenshot 2024-10-24 at 5 51 27 PM](https://github.com/user-attachments/assets/46be451d-e48e-486d-abb4-95ed1fd1ca81)

**Comment by spaculusaninja** [comment]
![Screenshot 2024-10-24 at 5 51 27 PM](https://github.com/user-attachments/assets/de78c94f-6c6e-468f-ae49-f205a24b9a88)

**Comment by spaculusaninja** [comment]
![Screenshot 2024-10-24 at 6 01 31 PM](https://github.com/user-attachments/assets/5ef89de6-fec4-40ec-b70c-cb4cb2a1105e)

**Comment by spaculusaninja** [comment]
Here are screenshots.
![Screenshot 2024-10-24 at 5 51 27 PM](https://github.com/user-attachments/assets/2a3fd0d6-46f6-4b4e-9849-73cc8b0fab74)
![Screenshot 2024-10-24 at 6 01 31 PM](https://github.com/user-attachments/assets/893af271-d11e-4975-b8fa-2d714789eba0)
![Screenshot 2024-10-24 at 6 04 37 PM](https://github.com/user-attachments/assets/ae6534f1-c92c-428f-8a2d-e28f5c86c234)

**Comment by spaculusaninja** [comment]
"Hi [@mhuynh5757](https://github.com/mhuynh5757),
Thank you for your quick response and for working on the fix. I appreciate your efforts to merge the solution to the main branch and plan for a release this week.
Following your suggestion, I decided to test the 'task/disable-firebase-service' branch. I carefully followed the instructions provided in the documentation (https://github.com/twilio/twilio-voice-react-native/blob/main/docs/out-of-band-firebase-messaging-service.md). However, I'm still experiencing issues with push notifications and incoming calls in the Voice React Native SDK.
Could you please provide any additional troubleshooting steps or insights that might help resolve these persistent issues? Are there any known limitations or specific configurations that I should be aware of when testing this branch?

**Comment by spaculusaninja** [comment]
"Hi [@mhuynh5757](https://github.com/mhuynh5757),
Thank you for your quick response and for working on the fix. I appreciate your efforts to merge the solution to the main branch and plan for a release this week.
Following your suggestion, I decided to test the 'task/disable-firebase-service' branch. I carefully followed the instructions provided in the documentation (https://github.com/twilio/twilio-voice-react-native/blob/main/docs/out-of-band-firebase-messaging-service.md). However, I'm still experiencing issues with push notifications and incoming calls in the Voice React Native SDK.
Could you please provide any additional troubleshooting steps or insights that might help resolve these persistent issues? Are there any known limitations or specific configurations that I should be aware of when testing this branch?

**Comment by mhuynh5757** [comment]
Could you share the parameter value that you're passing to `voice.handleFirebaseMessage` when you encounter this error? You can just share the keys/structure, the values of the object can be redacted for your privacy.

**Comment by spaculusaninja** [comment]
Hi mhuynh5757,
I’m not receiving any remoteMessage notifications in either the foreground or background. I also tested the setup using [this tool](https://www.testfcm.in/), but I still don’t receive any notifications.
Any advice on troubleshooting steps would be really helpful. Thanks!

**Comment by mhuynh5757** [comment]
Hi @spaculusaninja, just to confirm, you're using the `@react-native-firebase/messaging` package? And you have something like
```
import messaging from '@react-native-firebase/messaging';

messaging().onMessage(async (remoteData) => {
  ...
});
```
in your application somewhere?

It's best to have this invocation as early as possible in your application lifecycle, as noted in the docs. Could you add a console log to help us debug?

```
messaging().onMessage(async (remoteData) => {
  console.log(remoteData.data);
});
```

Or is the issue that this function is not firing at all?

**Comment by spaculusaninja** [comment]
Hi @mhuynh5757,

Yes, I am using the @react-native-firebase/messaging package, and I have included this in my application:

import messaging from '@react-native-firebase/messaging';

messaging().onMessage(async (remoteData) => {
  console.log(remoteData.data); // Added console log for debugging
});

However, the issue is that messaging().onMessage() is not firing at all. I’ve already placed this invocation early in the application lifecycle to ensure it initializes as soon as possible.

I've also double-checked permissions and tried adding console logs to debug, but still no response from the onMessage function. Any additional suggestions on troubleshooting would be appreciated!

Thanks in advance for the help!

**Comment by mhuynh5757** [comment]
Hi @spaculusaninja I see. Unfortunately, this package is not within the scope of our project, it is a 3rd party package after all. I can try to assist you as much as possible, but I cannot help you with bugs in packages not our own.

Can you try to uninstall your app and reinstall it on your device? When Firebase messaging services declare listeners, they use an FCM Device token internally. Reinstalling the app forces this token to refresh. It may help your situation.

Also, we released `1.2.1` today, so you no longer have to use a pre-release version from the branch. Please upgrade at your earliest convenience, thanks for your patience!

**Comment by spaculusaninja** [comment]
Hi @mhuynh5757,

Thank you for the update and the recommendation! I’ve successfully updated to version 1.2.1 of @twilio/voice-react-native-sdk, and I also reinstalled the app to refresh the FCM Device token. Notifications are now working fine, but I’m still experiencing issues with incoming calls – they don’t seem to come through even after the successful registration for incoming calls.

I’ve double-checked the setup and ensured all listeners and permissions are configured as recommended. Is there any additional troubleshooting you’d suggest to resolve the incoming call issue, or any specific logs that might help identify the problem?

Thanks again for your support!

Here is Access token :- 
accessToken----- eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzMyZmYwOWUxNWVjY2MwZTg1OTc2Yjg1Nzk1MjE1YjZjLTE3MzA3MjY4NzQiLCJpc3MiOiJTSzMyZmYwOWUxNWVjY2MwZTg1OTc2Yjg1Nzk1MjE1YjZjIiwic3ViIjoiQUMzNmJjZTRmNjc5Yzk2OWZjMTk4MGE2N2I4MmI0OTVmNCIsImV4cCI6MTczMDczMDQ3NCwiZ3JhbnRzIjp7ImlkZW50aXR5IjoiZGVtb18xIiwidm9pY2UiOnsiaW5jb21pbmciOnsiYWxsb3ciOnRydWV9LCJvdXRnb2luZyI6eyJhcHBsaWNhdGlvbl9zaWQiOiJBUDU4Y2IzNDNhZTljMTE0ZDVhOTAwOGIwZWQ5ZjY4M2ViIn0sInB1c2hfY3JlZGVudGlhbF9zaWQiOiJDUjEzOGMzNTUyOTJmNDRkM2NiNDQxMjY4MDc0NDE5NWY4In19fQ.eRIGstbUk0lbp_d5SFL0SwSX_yl3324sftTVyj63pRQ

**Comment by spaculusaninja** [comment]
![Screenshot 2024-11-04 at 6 58 35 PM](https://github.com/user-attachments/assets/a4fcddf2-2a62-476e-b1b2-862bd2ef60d2)

**Comment by spaculusaninja** [comment]
![Screenshot 2024-11-04 at 7 00 01 PM](https://github.com/user-attachments/assets/2b0d40d7-fc78-408b-9a3c-ad9d2da2bb68)

**Comment by spaculusaninja** [comment]
![Screenshot 2024-11-04 at 7 02 04 PM](https://github.com/user-attachments/assets/c185fc56-4484-44ea-b3aa-c5a1e3b8c27b)

**Comment by spaculusaninja** [comment]
Here is Notification payload receive from FCM :- 
remoteMessage------ {"collapseKey": "com.aninja", "data": {"ignoreInForeground": "true", "notif_trigger_local": "1", "notif_type": "silent", "sub_message": "Missed call"}, "from": "169349367722", "messageId": "0:1730727254720565%2a1733d62a1733d6", "notification": {"android": {}, "body": "Missed call", "title": "Missed call - Auto-created from Missed Call (+16179152997)"}, "originalPriority": 1, "priority": 1, "sentTime": 1730727254712, "ttl": 2419200}

**Comment by spaculusaninja** [comment]
Here is error log screenshots
![Screenshot 2024-11-04 at 7 09 07 PM](https://github.com/user-attachments/assets/d19f9cdb-d8c3-4d93-ae1b-ac06ec35554a)

**Comment by spaculusaninja** [comment]
Here is call log screenshot
![Screenshot 2024-11-04 at 7 11 34 PM](https://github.com/user-attachments/assets/daddac85-7fce-4b2d-ab4e-688b9da1ed57)

**Comment by mhuynh5757** [comment]
Hello @spaculusaninja thanks for the additional info. It seems like you're receiving Firebase messages unrelated to Twilio, and it's causing parsing errors expectedly. Here's an example of a Firebase message that will be parsed correctly:

```
{
  "twi_account_sid": "",
  "twi_answer_timeout": "",
  "twi_bridge_token": "",
  "twi_call_sid": "",
  "twi_from": "",
  "twi_message_id": "",
  "twi_message_type": "",
  "twi_params": "",
  "twi_to": ""
}
```

I recommend that you do some checks in your application code to ensure that the data that you pass to `voice.handleFirebaseMessage` has that exact structure (of course the values of the record have been redacted, but the keys are as they should be).

**Comment by spaculusaninja** [comment]
Hi @mhuynh5757,

Thank you for the clarification and example message structure. 

Could you please confirm if there are any additional required fields or permissions on the Android sid

**Comment by spaculusaninja** [comment]
![Screenshot 2024-11-06 at 7 20 39 PM](https://github.com/user-attachments/assets/18fbfb98-2230-465d-aeab-3def96dc2358)

**Comment by spaculusaninja** [comment]
![Screenshot 2024-11-06 at 7 21 42 PM](https://github.com/user-attachments/assets/b2fd4513-602a-4197-8e11-3fcb868a7e5b)

**Comment by mhuynh5757** [comment]
That looks more than sufficient. If you need any examples for those files, you can check the Test App that we use to test the RN SDK which can be found under `test/app/` or the Reference App. You can find more about the Reference App in our Readme.

**Comment by spaculusaninja** [comment]
Hi @mhuynh5757,

Thank you for the suggestion! I’ve set up the config as mentioned in the SDK documentation, and everything seems to be configured correctly. However, I’m still experiencing issues with calls not working as expected. Could you provide any guidance or troubleshooting steps that might help pinpoint the issue? Additionally, if there are any specific parts of the Test App or Reference App you recommend for checking configuration, I’d appreciate it.

**Comment by mhuynh5757** [comment]
Hey @spaculusaninja can you please provide more details on "calls not working as expected"? Is it incoming calls, or outgoing calls now? I'm assuming you're still having trouble with incoming calls? Are you still performing `await voice.register()`? Do you see the Firebase message handlers fire, and the `remoteMessage.data` have the form that I detailed above?

**Comment by spaculusaninja** [comment]
Hi @mhuynh5757,

Thanks for following up! Here’s an update on the issues I’m experiencing:

### **1.Incoming Calls Not Working:**
- I’m still having trouble with incoming calls. I’ve gone through all recommended steps, including:
Updating to the latest SDK.
Configuring FCM with V1 settings.
Setting up Twilio push credentials.
Successfully calling await voice.register() with the token.

- FCM notifications work correctly when tested directly from the FCM Console, but incoming call notifications aren’t triggering. It seems like the Firebase message handlers aren’t firing as expected for Twilio call notifications.

**### 2.Outgoing Calls Issue:**

- When trying to make an outgoing call using await voice.connect(accessToken, { params: params });, where params = { 
    "To": "+17817467047" }, I receive a response that’s missing critical fields:
     _from and _to fields are undefined.
     _sid is also undefined, with _state showing “connecting.”

- The response contains function placeholders (e.g., _handleConnectFailureEvent, _handleConnectedEvent) without completing the connection process, resulting in the call being classified as “unknown.”

**Comment by spaculusaninja** [comment]
Here is params---- {"To": "+17817467047"}

**Comment by spaculusaninja** [comment]
Here is response :- 
{
  "_customParameters": {
    
  },
  "_events": {
    
  },
  "_eventsCount": 0,
  "_from": undefined,
  "_handleConnectFailureEvent": [
    Functionanonymous
  ],
  "_handleConnectedEvent": [
    Functionanonymous
  ],
  "_handleDisconnectedEvent": [
    Functionanonymous
  ],
  "_handleMessageReceivedEvent": [
    Functionanonymous
  ],
  "_handleNativeEvent": [
    Functionanonymous
  ],
  "_handleQualityWarningsChangedEvent": [
    Functionanonymous
  ],
  "_handleReconnectedEvent": [
    Functionanonymous
  ],
  "_handleReconnectingEvent": [
    Functionanonymous
  ],
  "_handleRingingEvent": [
    Functionanonymous
  ],
  "_initialConnectedTimestamp": undefined,
  "_isMuted": false,
  "_isOnHold": false,
  "_nativeEventHandler": {
    "callEventConnectFailure": [
      Functionanonymous
    ],
    "callEventConnected": [
      Functionanonymous
    ],
    "callEventDisconnected": [
      Functionanonymous
    ],
    "callEventMessageReceived": [
      Functionanonymous
    ],
    "callEventQualityWarningsChanged": [
      Functionanonymous
    ],
    "callEventReconnected": [
      Functionanonymous
    ],
    "callEventReconnecting": [
      Functionanonymous
    ],
    "callEventRinging": [
      Functionanonymous
    ]
  },
  "_sid": undefined,
  "_state": "connecting",
  "_to": undefined,
  "_uuid": "f46d49b7-5404-4b2e-86ee-f002064b9665"
}

**Comment by mhuynh5757** [comment]
Let's try something to verify that your Twilio credentials and configs are set up properly. Can you please run the Test App that's built into this repo under `test/app/`? If you can receive incoming calls with the Test App, that may provide some helpful information.

**Comment by anhtrung87vn** [comment]
Hi @mhuynh5757 ,

Could you let me know what is twi_bridge_token? I searched it on twilio doc but did not find out.
When does twi_bridge_token create?
Because when I make a call to twilio number, then trigger webhook to my server , and capture log, I see that the format is as below. I don't see bridge token. 
{
    "Called": "",
    "ToState": "",
    "CallerCountry": "LS",
    "Direction": "inbound",
    "CallerState": "",
    "ToZip": "",
    "CallSid": "CA66a8a0dcccab9934693284015fc17f1c",
    "To": "",
    "CallerZip": "",
    "ToCountry": "",
    "CallToken": "%7B%22parentCallInfoToken%22%3A%22eyJhbGciOiJFUzI1NiJ9.eyJjYWxsU2lkIjoiQ0E2NmE4YTBkY2NjYWI5OTM0NjkzMjg0MDE1ZmMxN2YxYyIsImZyb20iOiJhbm9ueW1vdXMiLCJ0byI6Iis2MTQ0MDEzODUwNCIsImlhdCI6IjE3MzMzNzYxNzEifQ.D5RAvvcuqreqb9OH0MZFlVGbivgbdv_23fdsBkbEGODbJjLF7w0Kx6J66BO9RYqT5_ayRYKmPubbXa3eC5rvWg%22%2C%22identityHeaderTokens%22%3A%5B%5D%7D",
    "CalledZip": "",
    "ApiVersion": "2010-04-01",
    "CalledCity": "",
    "CallStatus": "ringing",
    "From": "anonymous",
    "AccountSid": "",
    "CalledCountry": "AU",
    "CallerCity": "",
    "ToCity": "",
    "FromCountry": "LS",
    "Caller": "anonymous",
    "FromCity": "",
    "CalledState": "",
    "FromZip": "",
    "FromState": ""
}
}

**Comment by WaseemAnjum8484** [comment]
when the outgoing call connect then they give us this response. incoming listener is also not working whereas webhooks are working fine.
sid and params are undefined. this is my code 
  const HandelCall = async (callToken: any, ProfileInfoData: any, userId: any) => {
    try {
  
      const Call = await voice.connect(callToken, {
        params: {
          From: ProfileInfoData?.userId,
          to: userId,
        },
      });
      console.log("connectResult_____________",Call)
 {"_customParameters": {}, "_events": {}, "_eventsCount": 0, "_from": undefined, "_handleConnectFailureEvent": [Function anonymous], "_handleConnectedEvent": [Function anonymous], "_handleDisconnectedEvent": [Function anonymous], "_handleMessageReceivedEvent": [Function anonymous], "_handleNativeEvent": [Function anonymous], "_handleQualityWarningsChangedEvent": [Function anonymous], "_handleReconnectedEvent": [Function anonymous], "_handleReconnectingEvent": [Function anonymous], "_handleRingingEvent": [Function anonymous], "_initialConnectedTimestamp": undefined, "_isMuted": false, "_isOnHold": false, "_nativeEventHandler": {"callEventConnectFailure": [Function anonymous], "callEventConnected": [Function anonymous], "callEventDisconnected": [Function anonymous], "callEventMessageReceived": [Function anonymous], "callEventQualityWarningsChanged": [Function anonymous], "callEventReconnected": [Function anonymous], "callEventReconnecting": [Function anonymous], "callEventRinging": [Function anonymous]}, "_sid": undefined, "_state": "connecting", "_to": undefined, "_uuid": "0a3755a7-e63a-4199-9532-c97583c20e35"}

**Comment by ViktorSyrotkin** [comment]
[spaculusaninja](https://github.com/spaculusaninja) Have you resolved the issue with incoming calls / pushes for Android?

**Comment by spaculusaninja** [comment]
I am facing an issue where making an outgoing call using the Twilio Voice SDK results in the same device receiving it as an incoming call. I am using @react-native-firebase/messaging to handle push notifications for incoming calls.

here is request param :- 
params----- {"ant": "aninja", "calleeName": "Contact_+17817467047", "from": "+16179152997", "sourcePhoneNumber": "+16179152997", "targetPhoneNumber": "+17817467047", "to": "+17817467047"}

here is response of incoming call on same device 
remoteMessage----- {"data": {"twi_account_sid": "AC36bce4f679c969fc1980a67b82b495f4", "twi_answer_timeout": "600", "twi_bridge_token": "eyJ6aXAiOiJERUYiLCJjdHkiOiJ0d2lsaW8tZnBhO3Y9MSIsImVuYyI6IkEyNTZHQ00iLCJhbGciOiJkaXIiLCJ0d3IiOiJ1czEiLCJraWQiOiJTQVNfUzNfX19LTVNfdjEifQ..ggd7fuJTwfPN05dA.G_wZ22ldqCJN_mVC2n0E0o8VBRK6WF7SfK3ztxK_1eGzTKuOYdrjsP6oqAtOXATdlOX_Bv8xD57Cl_B2MTRwadGDo_bzTgR5kbFLlwkE4aU0z6MlUYyYeSra6pSSHivqTeD3g-EhVNI6NhBHp2N6sCXAz1YKo4JmyDalP22jmF3zHsPhYucJpVTsCKyTygQSOWnHwgMvIAwEw8nx2-p2pNqNXKWC6p_ChAcMXOzquD3dBSno36LNIV2Knitwdqc6BNcag11Y_7Lt1vzxvgPEDvBJL8tEl8fdtJPG-TG_UMiHnskQhwKY_k87a1Q2Abj_XnN6KcbSv187_Hi5HrIjq7p5D1t1UJKlhpvEEG6okn1LMee6sHJmNW82N2TX17BkcCIsAnnDzHxC2DMUBxm0CzZB_PG9ygobX52GytNbPuwHlxDYQ6nIMD6pFSCdUzaJ3GbqEcgoJdYquRwzi7xQvUudUdWIymwUKtk8vJbZHtw-3-IIU4sNNt3NkmS2QTrgNa0iN0mSzQ7KO_Y-XcGeNMw.m6X5rrrAPxD9Cp4ui4SvHA", "twi_call_sid": "CAbe1e4cec659f3eabef5be6e56480f97a", "twi_from": "+16179152997", "twi_message_id": "RUec01e713d4847b52f7087bce5a2d0950", "twi_message_type": "twilio.voice.call", "twi_stir_status": "TN-Validation-Passed-B", "twi_to": "client:demo_1"}, "from": "169349367722", "messageId": "0:1735311525226969%2a1733d6f9fd7ecd", "originalPriority": 1, "priority": 1, "sentTime": 1735311525202, "ttl": 0}

**Comment by mhuynh5757** [comment]
Hi all, sorry for the delayed response. Let's see if I can dig further into this issue. @spaculusaninja when you set up `@react-native-firebase/messaging` like so
```
import messaging from '@react-native-firebase/messaging';
import { Voice } from '@twilio/voice-react-native-sdk';

const token = '...';
const voice = new Voice();
voice.register(token);

messaging().onMessage(async (remoteMessage) => {
  console.log(remoteMessage.data);
  voice.handleFirebaseMessage(remoteMessage.data); // important, note the `.data` here
});

messaging().setBackgroundMessageHandler(async (remoteMessage) => {
  console.log(remoteMessage.data);
  voice.handleFirebaseMessage(remoteMessage.data); // likewise, note the `.data` here
});
```
what do you see in the `console.log`s? You should see some subset of the messages appear with this format:
```
{
  "twi_account_sid": "",
  "twi_answer_timeout": "",
  "twi_bridge_token": "",
  "twi_call_sid": "",
  "twi_from": "",
  "twi_message_id": "",
  "twi_message_type": "",
  "twi_params": "",
  "twi_to": ""
}
```
These things are not documented as they are not intended to be public-facing. They are internal to the Twilio Android SDK. What normally happens is that the built-in Firebase messaging service in the Android SDK handles these values for you, but since we are using a third-party Firebase messaging service, these values need to be relayed from that third-party to the Twilio Android SDK.

**Comment by mhuynh5757** [comment]
To answer your questions about the outgoing calls, it appears that you are unable to successfully make outgoing calls from a client to a client/PSTN? There's not much utility in logging the result of `await voice.connect(...)`, especially the private underscore-prefixed values `_X`. Please use the public-facing APIs that the `call` class provides, such as `call.on(...)` to interact with the call.

**Comment by SridixDevMukesh** [comment]
Hello @mhuynh5757 ,
`const handleIncomingCallNotification = async(remoteMessage: any) => {`
   ` const data = remoteMessage.data;`
` try {`
      `  const didHandleMessage = await voice.handleFirebaseMessage(data);`
      `  console.log("didHandleMessage", didHandleMessage);`
      ` } catch (error) {`
      `  console.log("didHandleMessage error", JSON.stringify(error));`
     ` }`
`}`
Unable to get incoming call, got this error in console:-
didHandleMessage error {"nativeStackAndroid":[],"userInfo":null,"message":"Method invocation invalid","code":"EUNSPECIFIED"}

**Comment by mhuynh5757** [comment]
@SridixDevMukesh are you following this guide? https://github.com/twilio/twilio-voice-react-native/blob/main/docs/out-of-band-firebase-messaging-service.md#disabling-the-built-in-firebase-messaging-service

Please ensure that you add the boolean to your XML files to disable the built-in service.

**Comment by spaculusaninja** [comment]
Hi mhuynh5757,

I’m facing an issue on iOS with Twilio incoming calls in my project. When using the development profile (debug mode), incoming calls work as expected. However, in release mode (distribution profile), they stop working after I uncheck the "Sandbox" option in the Twilio Push Credentials.

Is there any configuration or step I might be missing to ensure incoming calls work properly in release mode on iOS?

Thanks for your help!

**Comment by mhuynh5757** [comment]
Hey @spaculusaninja sorry for the late response, I apologize. Talking to my iOS teammate, we recommend a different APNs push notification credential for your prod environment. If you are still having issues, please provide a CallSID and we can dig deeper.

**Comment by mhuynh5757** [comment]
Hey all, going to close this one as stale for now. Please feel free to reach out if you need further assistance.

**Comment by BathulaNikhil** [comment]
Hi @mhuynh5757 I'm facing incoming call issue my getting the incoming message data from FCM notification 
But i can show the incoming screen and the call invite or not working 
this is my json fromat : 
{
  "twi_account_sid": "",
  "twi_answer_timeout": "",
  "twi_bridge_token": "",
  "twi_call_sid": "",
  "twi_from": "",
  "twi_message_id": "",
  "twi_message_type": "",
  "twi_params": "",
  "twi_to": ""
}

**Comment by mhuynh5757** [comment]
Hey @BathulaNikhil it's better to open new issues for visibility. You need to pass that object to the `voice.handleMessage` API as per our https://github.com/twilio/twilio-voice-react-native/blob/main/docs/out-of-band-firebase-messaging-service.md guide.
